---

extends: default

rules:
  line-length:
    max: 120
  empty-lines:
    level: warning
    max-end: 1
  quoted-strings:
    quote-type: single
    required: false
  indentation:
    spaces: 2
    indent-sequences: consistent
  document-start: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable

ignore:
  node_modules/
  test/
  tests/
  data/
  build/
  dist/
  sources/workflows/workflows/categories.yml
  sources/workflows/subworkflows/categories.yml
  sources/materials/categories.yml
  sources/applications/categories.yml
  sources/properties/categories.yml
  sources/methods/categories.yml
  sources/models/categories.yml
  sources/applications/applications/
