#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Extract z-coordinate boundaries from materials for polar VBO calculation.

Reads structure from pw_scf.out file using ASE and extracts z-coordinates.
"""
import json
import os

import numpy as np
import ase.io
from mat3ra.made.material import Material
from mat3ra.made.tools.convert import from_ase

# Material index: 0=Interface, 1=Left, 2=Right
{% raw %}material_index = int({{material_index}}){% endraw %}

# Read structure from pw_scf.out (generated by previous pw_scf calculation)
pw_scf_output = "./pw_scf.out"

if not os.path.exists(pw_scf_output):
    # Fallback if file doesn't exist
    print(json.dumps({
        "error": "pw_scf.out not found",
        "slab1_min": 0.0,
        "slab1_max": 20.0,
        "slab2_min": 0.0,
        "slab2_max": 20.0,
        "material_index": material_index,
    }, indent=4))
    exit(0)

# Read atomic structure from espresso output
atoms = ase.io.read(pw_scf_output, format="espresso-out")

# Convert ASE Atoms to Material using mat3ra-made
material = Material.create(from_ase(atoms))

# Extract z-coordinates
coordinates = material.basis.coordinates
z_coords_frac = np.array(coordinates.get_values_along_axis(axis="z"))

# Convert to Cartesian (Angstroms)
c_length = material.lattice.c
z_coords_angstrom = z_coords_frac * c_length

# Extract z-range
z_min = np.min(z_coords_angstrom)
z_max = np.max(z_coords_angstrom)

result = {
    "slab1_min": float(z_min),
    "slab1_max": float(z_max),
    "slab2_min": float(z_min),
    "slab2_max": float(z_max),
    "material_index": material_index,
}

print(json.dumps(result, indent=4))
